# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/assess.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpb/assess.proto\"!\n\rAssessRequest\x12\x10\n\x03img\x18\x01 \x01(\x0cR\x03img\"@\n\x0e\x41ssessResponse\x12\x14\n\x05score\x18\x01 \x01(\x02R\x05score\x12\x18\n\x07\x63omment\x18\x02 \x01(\tR\x07\x63omment2:\n\rAssessService\x12)\n\x06\x41ssess\x12\x0e.AssessRequest\x1a\x0f.AssessResponseB\nZ\x08.;assessb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.assess_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010.;assess'
  _globals['_ASSESSREQUEST']._serialized_start=19
  _globals['_ASSESSREQUEST']._serialized_end=52
  _globals['_ASSESSRESPONSE']._serialized_start=54
  _globals['_ASSESSRESPONSE']._serialized_end=118
  _globals['_ASSESSSERVICE']._serialized_start=120
  _globals['_ASSESSSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
