spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/inkin?autoreconnect=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"

inkin:
  server-url: "http://localhost:8080/"