# 使用官方的nginx镜像作为基础镜像
FROM nginx:latest

# 将你的静态资源复制到nginx的默认静态资源目录
COPY ./dist/ /usr/share/nginx/html/

# 指定nginx的配置文件
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# 暴露80端口
EXPOSE 80

# 启动nginx
CMD ["nginx", "-g", "daemon off;"]